# Generated by Django 5.0.7 on 2024-07-30 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=100)),
                ('bought_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.ForeignKey(db_column='phone_number', on_delete=django.db.models.deletion.CASCADE, to='App.credent')),
            ],
            options={
                'db_table': 'portfolio',
            },
        ),
    ]
