# Generated by Django 5.0.7 on 2024-07-30 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.ForeignKey(db_column='phone_number', on_delete=django.db.models.deletion.CASCADE, to='App.credent')),
            ],
        ),
    ]
