# Generated by Django 5.0.7 on 2024-07-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=500000.0, max_digits=10),
        ),
    ]
