# Generated by Django 5.0.7 on 2024-07-30 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_balance_balance_amount'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='balance',
            table='balance',
        ),
    ]
