# Generated by Django 5.0.7 on 2024-08-06 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_balance_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='phone_number',
        ),
        migrations.DeleteModel(
            name='balance',
        ),
        migrations.DeleteModel(
            name='portfolio',
        ),
    ]
