version: "3.10-slim"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1

  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "5001:5000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    environment:
      - API_KEY=${API_KEY}
